### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by 90sCraig** [Anthchirp/mastodon-defederate#1]
This is very likely user error, but I have installed the package via pip and get the following when trying to use it:

`
Traceback (most recent call last):
  File "/usr/local/bin/defederate", line 5, in <module>
    from defederate.cli import main
ModuleNotFoundError: No module named 'defederate'
root@localhost:~# nano /usr/local/bin/defederate
`

Any tips?

**Comment by aetaric** [comment]
Gonna plus one this. It's happening for me as well.

**Comment by fouquet** [comment]
Same issue for me unfortunately :(

**Comment by Anthchirp** [comment]
Yes, the package layout was broken. Consequence of not actually having any tests yet.
I'm supposedly a software engineer, so since this package has gathered massive attention I might have to do this properly 😁 

Fixed in 0.1.1
